version: 2
updates:
  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dashboard-production:
        dependency-type: production
      dashboard-development:
        dependency-type: development
  - package-ecosystem: npm
    directory: /dashboard/website
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
