/** Canonical list of all Kecktech stack services.
 *  Single source of truth for home page tiles, ops page, and /api/health.
 *  Health checks ping Traefik by IP from inside Docker (cannot hairpin public DNS),
 *  with healthHost set to the real vhost for name-based routing.
 */
export type ServiceDef = {
  name: string;
  description: string;
  url: string;
  healthUrl: string;
  healthHost?: string;
  icon: string;
  color: string;
  logoUrl?: string;
  /** When true, skip live health ping and always show a static "Running" badge */
  noHealthCheck?: boolean;
};

/** Traefik LAN IP reachable from dashboard containers on kecktech_front */
const TRAEFIK = "https://10.20.0.100";

function viaTraefik(host: string, path = "/"): Pick<ServiceDef, "healthUrl" | "healthHost"> {
  return {
    healthUrl: `${TRAEFIK}${path}`,
    healthHost: host,
  };
}

function brand(host: string, path = "/"): Pick<ServiceDef, "healthUrl" | "healthHost" | "noHealthCheck"> {
  // Brand domains hairpin poorly from dash containers — health via public URL with noHealthCheck false
  // uses external fetch in health API when healthHost omitted; keep explicit URL for ops.
  return {
    healthUrl: `https://${host}${path}`,
    noHealthCheck: false,
  };
}

export const SERVICES: ServiceDef[] = [
  // —— Core ops ——
  {
    name: "Ops Dashboard",
    description: "dash.kecktech.net",
    url: "https://dash.kecktech.net",
    ...viaTraefik("dash.kecktech.net", "/"),
    icon: "monitor",
    color: "#C07810",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "ERPNext",
    description: "CRM · Billing · HaaS Fleet",
    url: "https://erp.kecktech.net",
    ...viaTraefik("erp.kecktech.net", "/api/method/ping"),
    icon: "briefcase",
    color: "#0089ff",
    logoUrl: "/logos/erpnext.png",
  },
  {
    name: "Zammad",
    description: "White Glove Help Desk",
    url: "https://tickets.kecktech.net",
    ...viaTraefik("tickets.kecktech.net", "/api/v1/signshow"),
    icon: "headset",
    color: "#0D6E6E",
    logoUrl: "/logos/zammad.svg",
  },
  {
    name: "Vaultwarden",
    description: "Sovereign Secrets Vault",
    url: "https://vault.kecktech.net",
    ...viaTraefik("vault.kecktech.net", "/alive"),
    icon: "lock",
    color: "#818cf8",
    logoUrl: "/logos/vaultwarden.svg",
  },
  {
    name: "n8n",
    description: "Workflow Automation",
    url: "https://n8n.kecktech.net",
    ...viaTraefik("n8n.kecktech.net", "/healthz"),
    icon: "workflow",
    color: "#ff6d5a",
    logoUrl: "/logos/n8n.png",
  },
  {
    name: "Kecktech Website",
    description: "www.kecktech.net — Astro Static Site",
    url: "https://www.kecktech.net",
    ...viaTraefik("www.kecktech.net", "/"),
    icon: "globe",
    color: "#C07810",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Kecktech Admin",
    description: "CMS editor (admin.kecktech.net)",
    url: "https://admin.kecktech.net",
    ...viaTraefik("admin.kecktech.net", "/"),
    icon: "edit",
    color: "#1E3A5F",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Custom Wiki",
    description: "Kecktech Help Center (also serves wiki/docs aliases)",
    url: "https://help.kecktech.net",
    ...viaTraefik("help.kecktech.net", "/api/health"),
    icon: "book",
    color: "#0D6E6E",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Umami",
    description: "Privacy-First Analytics",
    url: "https://stats.kecktech.net",
    ...viaTraefik("stats.kecktech.net", "/api/heartbeat"),
    icon: "chart",
    color: "#f59e0b",
    logoUrl: "/logos/umami.png",
  },
  {
    name: "Tactical RMM",
    description: "Remote Monitoring & Management",
    url: "https://rmm.kecktech.net",
    ...viaTraefik("rmm.kecktech.net", "/"),
    icon: "monitor",
    color: "#6366f1",
    logoUrl: "/logos/trmm.svg",
  },
  {
    name: "TRMM API",
    description: "api.kecktech.net",
    url: "https://api.kecktech.net",
    ...viaTraefik("api.kecktech.net", "/"),
    icon: "workflow",
    color: "#6366f1",
    logoUrl: "/logos/trmm.svg",
  },
  {
    name: "MeshCentral",
    description: "mesh.kecktech.net",
    url: "https://mesh.kecktech.net",
    ...viaTraefik("mesh.kecktech.net", "/"),
    icon: "monitor",
    color: "#0ea5e9",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Portainer",
    description: "Container Management",
    url: "https://portainer.kecktech.net",
    ...viaTraefik("portainer.kecktech.net", "/"),
    icon: "container",
    color: "#13bef9",
    logoUrl: "/logos/portainer.png",
  },
  {
    name: "Traefik",
    description: "Reverse Proxy",
    url: "https://traefik.kecktech.net",
    ...viaTraefik("traefik.kecktech.net", "/ping"),
    icon: "route",
    color: "#38a3a5",
    logoUrl: "/logos/traefik.png",
  },
  {
    name: "Authelia",
    description: "SSO Gateway",
    url: "https://auth.kecktech.net",
    ...viaTraefik("auth.kecktech.net", "/api/health"),
    icon: "shield",
    color: "#1a56db",
    logoUrl: "/logos/authelia.png",
  },
  {
    name: "LLDAP",
    description: "User Directory & SSO Accounts",
    url: "https://lldap.kecktech.net",
    ...viaTraefik("lldap.kecktech.net", "/"),
    icon: "users",
    color: "#7c3aed",
    logoUrl: "/logos/lldap.svg",
  },
  {
    name: "RustDesk",
    description: "Primary Remote Support (hosted)",
    url: "https://rustdesk.kecktech.net",
    healthUrl: "",
    noHealthCheck: true,
    icon: "remote",
    color: "#e05c28",
    logoUrl: "/logos/rustdesk.svg",
  },
  {
    name: "Customer Portal",
    description: "Client account portal",
    url: "https://portal.kecktech.net",
    ...viaTraefik("portal.kecktech.net", "/"),
    icon: "globe",
    color: "#0D6E6E",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Brain",
    description: "brain.kecktech.net",
    url: "https://brain.kecktech.net",
    ...viaTraefik("brain.kecktech.net", "/"),
    icon: "shield",
    color: "#7c3aed",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Hub",
    description: "hub.kecktech.net",
    url: "https://hub.kecktech.net",
    ...viaTraefik("hub.kecktech.net", "/"),
    icon: "workflow",
    color: "#38a3a5",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Session",
    description: "session.kecktech.net",
    url: "https://session.kecktech.net",
    ...viaTraefik("session.kecktech.net", "/"),
    icon: "monitor",
    color: "#1B6B93",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Mom Hub",
    description: "mom-hub.kecktech.net",
    url: "https://mom-hub.kecktech.net",
    ...viaTraefik("mom-hub.kecktech.net", "/"),
    icon: "globe",
    color: "#db2777",
    logoUrl: "/logos/kecktech.svg",
  },
  // —— Demos / apps ——
  {
    name: "Marketlist",
    description: "Household food system demo",
    url: "https://marketlist.kecktech.net",
    ...viaTraefik("marketlist.kecktech.net", "/"),
    icon: "globe",
    color: "#2E7D32",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "FloorOS",
    description: "Flooring ops companion for RFMS",
    url: "https://flooros.kecktech.net",
    ...viaTraefik("flooros.kecktech.net", "/"),
    icon: "globe",
    color: "#C07810",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Argo",
    description: "In-house operations board",
    url: "https://argo.kecktech.net",
    ...viaTraefik("argo.kecktech.net", "/"),
    icon: "workflow",
    color: "#1E3A5F",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Cleaner",
    description: "Repo cleanup tool",
    url: "https://cleaner.kecktech.net",
    ...viaTraefik("cleaner.kecktech.net", "/"),
    icon: "edit",
    color: "#6366f1",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "NetOps",
    description: "Fleet control",
    url: "https://net-ops.kecktech.net",
    ...viaTraefik("net-ops.kecktech.net", "/"),
    icon: "monitor",
    color: "#1B6B93",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Chat",
    description: "Open WebUI — Kecktech AI",
    url: "https://chat.kecktech.net",
    ...viaTraefik("chat.kecktech.net", "/"),
    icon: "headset",
    color: "#7c3aed",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Sovereign Hub",
    description: "AI infrastructure hub",
    url: "https://sovereign-hub.kecktech.net",
    ...viaTraefik("sovereign-hub.kecktech.net", "/"),
    icon: "shield",
    color: "#38a3a5",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Sovereign Session",
    description: "sovereign-session.kecktech.net",
    url: "https://sovereign-session.kecktech.net",
    ...viaTraefik("sovereign-session.kecktech.net", "/"),
    icon: "shield",
    color: "#0f766e",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "FarmBot",
    description: "FarmBot web app demo",
    url: "https://farmbot.kecktech.net",
    ...viaTraefik("farmbot.kecktech.net", "/"),
    icon: "globe",
    color: "#2E7D32",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "AeroCAD",
    description: "CAD CM / document control demo",
    url: "https://aerocad.kecktech.net",
    ...viaTraefik("aerocad.kecktech.net", "/"),
    icon: "edit",
    color: "#0089ff",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "RateMyRack",
    description: "Home lab rack community",
    url: "https://ratemyrack.kecktech.net",
    ...viaTraefik("ratemyrack.kecktech.net", "/"),
    icon: "globe",
    color: "#6366f1",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Lost in Thought",
    description: "Huxley fiction editor",
    url: "https://lostinthought.kecktech.net",
    ...viaTraefik("lostinthought.kecktech.net", "/"),
    icon: "book",
    color: "#5b4a3f",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Asset Forge",
    description: "Art / asset generation inbox",
    url: "https://forge.kecktech.net",
    ...viaTraefik("forge.kecktech.net", "/"),
    icon: "edit",
    color: "#e05c28",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "GPU Broker",
    description: "Cooling Tower · VRAM leases",
    url: "https://gpu.kecktech.net",
    ...viaTraefik("gpu.kecktech.net", "/"),
    icon: "monitor",
    color: "#38a3a5",
    logoUrl: "/logos/kecktech.svg",
  },
  // —— Newly discovered 2026-08-16 audit (no Traefik route / not yet health-checked) ——
  {
    name: "OpenBao",
    description: "Secrets management (Vault fork)",
    url: "",
    healthUrl: "",
    noHealthCheck: true,
    icon: "lock",
    color: "#8b5cf6",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "SillyTavern",
    description: "Purpose not yet documented",
    url: "",
    healthUrl: "",
    noHealthCheck: true,
    icon: "headset",
    color: "#7c3aed",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Conan Exiles Server",
    description: "Game server (ports 7777-7778, 27015)",
    url: "",
    healthUrl: "",
    noHealthCheck: true,
    icon: "monitor",
    color: "#c45c26",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Plex",
    description: "Media server (LXC)",
    url: "",
    healthUrl: "",
    noHealthCheck: true,
    icon: "globe",
    color: "#e5a00d",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "MediaTools",
    description: "Music Assistant, Audiobookshelf, *arr stack (LXC)",
    url: "",
    healthUrl: "",
    noHealthCheck: true,
    icon: "container",
    color: "#0ea5e9",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Postiz",
    description: "Social scheduling (part of Me Manager stack)",
    url: "http://10.20.0.205:4007/launches",
    healthUrl: "",
    noHealthCheck: true,
    icon: "workflow",
    color: "#C07810",
    logoUrl: "/logos/kecktech.svg",
  },
  // —— Presence / brand sites ——
  {
    name: "Will Work For Lunch",
    description: "Personal portfolio + CMS",
    url: "https://willworkforlunch.com",
    ...brand("willworkforlunch.com"),
    icon: "globe",
    color: "#0ea5e9",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "ME Manager",
    description: "Presence OS · Inbox · Pipeline (dash SSO)",
    // me.kecktech.net shares Authelia cookie with dash — no second login.
    // Brand host me.willworkforlunch.com still works (separate WWFL portal).
    url: "https://me.kecktech.net",
    ...viaTraefik("me.kecktech.net", "/"),
    icon: "workflow",
    color: "#C07810",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Auth WWFL",
    description: "Authelia portal · willworkforlunch.com",
    url: "https://auth.willworkforlunch.com",
    ...brand("auth.willworkforlunch.com", "/api/health"),
    icon: "shield",
    color: "#1a56db",
    logoUrl: "/logos/authelia.png",
  },
  {
    name: "Jacob Roman",
    description: "Author site · Lost in Thought",
    url: "https://jacob-roman.com",
    ...brand("jacob-roman.com"),
    icon: "book",
    color: "#5b4a3f",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Auth Jacob",
    description: "Authelia portal · jacob-roman.com",
    url: "https://auth.jacob-roman.com",
    ...brand("auth.jacob-roman.com", "/api/health"),
    icon: "shield",
    color: "#1a56db",
    logoUrl: "/logos/authelia.png",
  },
  {
    name: "Uncle Jon's IT Garage",
    description: "Game studio marketing",
    url: "https://unclejonsitgarage.com",
    ...brand("unclejonsitgarage.com"),
    icon: "globe",
    color: "#c45c26",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "UJ CtrlPanel",
    description: "Game hosting panel",
    url: "https://panel.unclejonsitgarage.com",
    ...brand("panel.unclejonsitgarage.com"),
    icon: "monitor",
    color: "#1E3A5F",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Auth UJ",
    description: "Authelia portal · unclejonsitgarage.com",
    url: "https://auth.unclejonsitgarage.com",
    ...brand("auth.unclejonsitgarage.com", "/api/health"),
    icon: "shield",
    color: "#1a56db",
    logoUrl: "/logos/authelia.png",
  },
  // —— Site CMS admin panels — direct links, verified live 2026-08-16 ——
  {
    name: "WWFL Admin",
    description: "CMS admin · willworkforlunch.com",
    url: "https://willworkforlunch.com/admin",
    healthUrl: "",
    noHealthCheck: true,
    icon: "edit",
    color: "#0ea5e9",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "Jacob Roman Admin",
    description: "CMS admin · jacob-roman.com",
    url: "https://jacob-roman.com/admin",
    healthUrl: "",
    noHealthCheck: true,
    icon: "edit",
    color: "#5b4a3f",
    logoUrl: "/logos/kecktech.svg",
  },
  {
    name: "UJ Admin",
    description: "CMS admin · unclejonsitgarage.com",
    url: "https://unclejonsitgarage.com/admin",
    healthUrl: "",
    noHealthCheck: true,
    icon: "edit",
    color: "#c45c26",
    logoUrl: "/logos/kecktech.svg",
  },
];
